### ISSUE TITLE
Support for Selective Disclosure using bbs+ signatures

### ISSUE THREAD

**Issue by kenshin171** [spruceid/didkit#345] opened 2023-04-07 01:58 UTC
Thanks for your work on this library, may I ask whether selective disclosure with bbs+ signatures will be released anytime soon? 
I notice that there is work being done on both didkit and the ssi libraries.

**Comment by sbihel** [comment] 2023-04-11 17:08
DIDKit will gain support once `ssi` does. I will close this issue as duplicate of https://github.com/spruceid/ssi/issues/275, but may reopen once that issue is closed.

**Closed by sbihel** 2023-04-11 17:08 UTC
